### ISSUE TITLE
Terrain invisible when closing and returning to scene

### ISSUE THREAD

**Issue by HEofOttoman** [spimort/TerraBrush#101] opened 2024-05-21 08:14 UTC
Hello, i have an issue with the plugin when if I save and close the project and I come back later, the terrain disappears and turns invisible. Updating the terrain fixes the problem, but it also removed foliage that have been scattered with another plugin, spatial gardener. When this happens, when I open the project again I am in a different scene. This might mean this is caused when I save and close in another scene, but I am yet to do more testing

**Comment by HEofOttoman** [comment] 2024-05-21 08:31
This is also possibly caused by the spatial gardener plugin itself, so I will try updating the plugin and replicating the issue.

**Comment by Joy-less** [comment] 2024-05-21 21:33
I can confirm this happens without that plugin. You can also reload the scene to fix it.

**Comment by spimort** [comment] 2024-05-22 00:21
Alright! I'll check what could be the cause, I just had this issue as well, trying it.

**Comment by HEofOttoman** [comment] 2024-05-22 07:03
Can confirm that spatial gardener was not related to the issue. After updating, the foliage stayed existant, so this might be an issue that the creator of spatial gardener fixed

**Comment by HEofOttoman** [comment] 2024-05-22 08:17
I will open a new issue for spatial gardener as well.

**Comment by spimort** [comment] 2024-05-26 03:16
Hey @HEofOttoman , is there any way for you to test the branch fix/terrain-not-loading-if-not-active-scene, it should fix the problem but I'd like to make sure it works for you before I push it to main 🙂

**Comment by HEofOttoman** [comment] 2024-05-26 09:49
> Hey @HEofOttoman , is there any way for you to test the branch fix/terrain-not-loading-if-not-active-scene, it should fix the problem but I'd like to make sure it works for you before I push it to main 🙂

Ok sure, but one question, how do I update the plugin?

**Comment by spimort** [comment] 2024-05-26 13:52
Remove the terrabrush folder from your project and add the new downloaded one from GitHub (you can clone it or download a zip) 🙂

**Comment by spimort** [comment] 2024-05-28 11:00
Oh, I also answered, strange, don't you see the answer?

Anyways, here : 
Remove the terrabrush folder from your project and add the new downloaded one from GitHub (you can clone it or download a zip) 🙂

**Comment by HEofOttoman** [comment] 2024-05-29 07:05
ok thanks!

**Comment by HEofOttoman** [comment] 2024-05-29 07:42
Update: It seems to be fixed, but before I updated I could not replicate the issue

**Comment by HEofOttoman** [comment] 2024-05-30 01:23
Edit: Nope, the issue is back
![image](https://github.com/spimort/TerraBrush/assets/145900606/c949dff7-0bca-4227-af20-aae593421781)

**Comment by spimort** [comment] 2024-05-30 01:30
You are still on the the branch, right?
Make sure you compile the project as well (with the hammer button)

**Comment by HEofOttoman** [comment] 2024-05-30 04:09
yep,

**Comment by spimort** [comment] 2024-05-30 04:13
That is strange, is there anyway for you to share the project with me? Feel free to remove anything that you dont want to share, as long as I can reproduce the situation.

If needed, we can chat on discord, on my server (https://discord.gg/km99TVXEGr)

**Comment by spimort** [comment] 2024-06-04 02:35
@HEofOttoman  any news on that 🙂?

**Comment by HEofOttoman** [comment] 2024-06-07 05:50
I have joined the discord server

**Comment by spimort** [comment] 2024-06-15 16:30
@HEofOttoman Cool, I'm not sure I've seen you there but anyway, I did merge the pull request I was talking about (v0.7.1Alpha).
I think it fixes the issue but if it's not the case, a sample project would help a ton!

I'll wait to see if you can still reproduce it and in few days I'll close the issue if it's not the case (feel free to reopen one if needed 🙂)

**Closed** 2024-07-08 04:03 UTC
Labels: bug

**Comment by HEofOttoman** [comment] 2024-09-18 04:50
It seems to be fixed now, thank you very much
