### ISSUE TITLE
[Idea/Request] safe zones/areas

### ISSUE THREAD

**Issue by Schwagsone** [spimort/TerraBrush#99] opened 2024-05-16 17:40 UTC
Areas that cannot be modified

Mark an area with a brush or rectangle tool or even just a zone that cannot be modified. I think this would be useful for when you have completely beautified and finished an area with objects and the shape of terrain is exactly what you want so that it cannot be accidently modified with other areas that are being worked on. 

Perhaps the area is outline in red so you know which areas cannot be modified.

**Comment by lucasthomaz97** [comment] 2024-09-09 17:38
I'm making a racing game, and this would improve too much my workflow! Its too frequent when i want to change the height of something around the track and i end up messing the track itself...
If you could prioritize some enhancement, i would say this is the most important, at least to me.

**Comment by spimort** [comment] 2024-09-10 04:25
Sounds good, I'll check what I can do ! 🙂

**Comment by spimort** [comment] 2024-09-23 00:05
@Schwagsone @lucasthomaz97 any chance for you to try this branch?
https://github.com/spimort/TerraBrush/pull/142

It includes the new feature to paint "locked" areas

If you can, let me know how it goes!

**Comment by spimort** [comment] 2024-09-23 00:09
https://github.com/user-attachments/assets/bc752676-0f35-43ef-a855-f2802aeaa0b4

**Comment by lucasthomaz97** [comment] 2024-09-23 13:55
I tested it! The way it is now it feels usable already, one only thing that bothered me a little was that when i wanted to raise the surface around the locked area, it creates a unstable area, that i can manually go there and use smooth to unpixelate the edges, just like this print, maybe an "autosmooth" around the blocked area may help.
![image](https://github.com/user-attachments/assets/a2f52f6d-4e78-467a-9f26-5297269481a0)
Overall this helps me a lot with level and track design for my game! Thanks!

**Comment by spimort** [comment] 2024-09-24 04:17
@lucasthomaz97 Sounds good, I made an update in the same branch, could you try it? I think it's better now 🙂

It allows you to paint the locked area but smoothly.

**Comment by lucasthomaz97** [comment] 2024-09-24 09:26
I'll try it later

**Comment by lucasthomaz97** [comment] 2024-09-24 21:10
![image](https://github.com/user-attachments/assets/86f95439-cc24-4d7e-9487-eb569e06bca2)
I tried it, feels good, i just noticed that when i unlock an area by that button "unlock all" the texture gets affected and receives this "darken border".
at all it feels pretty good.

**Comment by spimort** [comment] 2024-09-25 02:48
Humm interesting!
Could it be because you painted texture while having locks?

The locks affect ALL the tools including the texture, so maybe you had partial locks there?

What happens if you reload Godot? Since everything is only in memory, it should refresh the whole map.

Let me know! 🙂
So far I was not able to reproduce it on my side

**Comment by spimort** [comment] 2024-09-27 20:59
I think I'll push this to main, if there are issues we could fix them later! 🙂

**Comment by spimort** [comment] 2024-09-27 23:44
This has been pushed to main, I'll close it for now. @lucasthomaz97  feel free to open an issue if you still have the one you were talking about 🙂

**Closed by spimort** 2024-09-27 23:44 UTC
Labels: enhancement
